-- MySQL Script generated by MySQL Workbench
-- Mon Jan 18 23:47:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(145) NOT NULL,
  `lastname` VARCHAR(145) NOT NULL,
  `phone_number` BIGINT(12) UNSIGNED NOT NULL,
  `email` VARCHAR(145) NOT NULL,
  `password_hash` CHAR(65) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profiles` (
  `Customer_id` INT UNSIGNED NOT NULL,
  `gender` ENUM('f', ' m', 'x') NOT NULL,
  `birthday` DATE NULL DEFAULT 'Не указано',
  `address` VARCHAR(245) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_Profiles_Customers_idx` (`Customer_id` ASC) VISIBLE,
  PRIMARY KEY (`Customer_id`),
  CONSTRAINT `fk_Profiles_Customers`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shop_seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shop_seller` (
  `User_id` INT UNSIGNED NOT NULL,
  `shop_name` VARCHAR(145) NOT NULL,
  `address` VARCHAR(245) NULL DEFAULT 'Только онлайн',
  `shop_phone` BIGINT(12) UNSIGNED NOT NULL,
  `shop_email` VARCHAR(145) NULL DEFAULT NULL,
  `shop_website` VARCHAR(145) NULL DEFAULT NULL,
  INDEX `fk_Shop_seller_Customers1_idx` (`User_id` ASC) VISIBLE,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `shop_name_UNIQUE` (`shop_name` ASC) VISIBLE,
  CONSTRAINT `fk_Shop_seller_Customers1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Goods` (
  `id_goods` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Shop_seller_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(145) NOT NULL,
  `category` VARCHAR(145) NULL DEFAULT 'Другое' COMMENT 'Тип товара ',
  `description` VARCHAR(45) NULL,
  `subcategory` VARCHAR(145) NULL,
  `quantity` BIGINT(10) UNSIGNED NULL DEFAULT 'Нет в наличии' COMMENT 'Колличество товара на складе',
  `description` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id_goods`),
  INDEX `fk_Goods_Shop_seller1_idx` (`Shop_seller_id` ASC) VISIBLE,
  CONSTRAINT `fk_Goods_Shop_seller1`
    FOREIGN KEY (`Shop_seller_id`)
    REFERENCES `mydb`.`Shop_seller` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shopping_cart` (
  `idShopping_cart` INT NOT NULL,
  `Customers_id` INT UNSIGNED NOT NULL,
  `Goods_id_goods` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`idShopping_cart`, `Customers_id`, `Goods_id_goods`),
  INDEX `fk_Shopping_cart_Customers1_idx` (`Customers_id` ASC) VISIBLE,
  INDEX `fk_Shopping_cart_Goods1_idx` (`Goods_id_goods` ASC) VISIBLE,
  CONSTRAINT `fk_Shopping_cart_Customers1`
    FOREIGN KEY (`Customers_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Shopping_cart_Goods1`
    FOREIGN KEY (`Goods_id_goods`)
    REFERENCES `mydb`.`Goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reviews` (
  `Users_id` INT UNSIGNED NOT NULL,
  `Goods_id_goods` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `rating` INT(5) NOT NULL DEFAULT 'Без оценки',
  `reviews_text` TEXT NULL,
  INDEX `fk_Reviews_Users1_idx` (`Users_id` ASC) VISIBLE,
  INDEX `fk_Reviews_Goods1_idx` (`Goods_id_goods` ASC) VISIBLE,
  CONSTRAINT `fk_Reviews_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reviews_Goods1`
    FOREIGN KEY (`Goods_id_goods`)
    REFERENCES `mydb`.`Goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Media_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Media_type` (
  `idMedia_type` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedia_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Media` (
  `idMedia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Media_type_idMedia_type` INT UNSIGNED NOT NULL,
  `Users_id` INT UNSIGNED NOT NULL,
  `Goods_id_goods` INT UNSIGNED NOT NULL,
  `file` VARCHAR(245) NULL DEFAULT NULL,
  `blob` BLOB NULL DEFAULT NULL,
  `size` BIGINT NULL DEFAULT NULL,
  `metadata` JSON NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idMedia`),
  INDEX `fk_Media_Media_type1_idx` (`Media_type_idMedia_type` ASC) VISIBLE,
  INDEX `fk_Media_Goods1_idx` (`Goods_id_goods` ASC) VISIBLE,
  INDEX `fk_Media_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Media_Media_type1`
    FOREIGN KEY (`Media_type_idMedia_type`)
    REFERENCES `mydb`.`Media_type` (`idMedia_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media_Goods1`
    FOREIGN KEY (`Goods_id_goods`)
    REFERENCES `mydb`.`Goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Favorites` (
  `Users_id` INT UNSIGNED NOT NULL,
  `Goods_id_goods` INT UNSIGNED NOT NULL,
  `add_at` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_Favorites_Users1_idx` (`Users_id` ASC) VISIBLE,
  INDEX `fk_Favorites_Goods1_idx` (`Goods_id_goods` ASC) VISIBLE,
  CONSTRAINT `fk_Favorites_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorites_Goods1`
    FOREIGN KEY (`Goods_id_goods`)
    REFERENCES `mydb`.`Goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Completed_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Completed_orders` (
  `Users_id` INT UNSIGNED NOT NULL,
  `Goods_id_goods` INT UNSIGNED NOT NULL,
  `when_ordered` DATETIME NOT NULL,
  `when_received` DATETIME NULL DEFAULT NULL,
  INDEX `fk_Completed_orders_Users1_idx` (`Users_id` ASC) VISIBLE,
  INDEX `fk_Completed_orders_Goods1_idx` (`Goods_id_goods` ASC) VISIBLE,
  CONSTRAINT `fk_Completed_orders_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Completed_orders_Goods1`
    FOREIGN KEY (`Goods_id_goods`)
    REFERENCES `mydb`.`Goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
